config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/services'
  get 'pages/testemonies'
  get 'pages/faq'
  get 'pages/contacts'

  get '/contacts', to: 'contacts#new'
  resources "contacts", only: [:new, :create]

  get "*path" => redirect("/")

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "maildomike@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def services
  end

  def testemonies
  end

  def faq
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Suse Site"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.haml
%div
  - flash.each do |key, value|
    %div
      %a{"data-dismiss" => "alert", :href => "#"} ×
      = value

app/views/contacts/new.html.haml
/ %div{:align => "center"}
%div
  %h3 Send a message to Us
  = simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f|
    = f.input :name, :required => true
    = f.input :email, :required => true
    = f.input :message, :as => :text, :required => true
    .hidden
      = f.input :nickname, :hint => 'Leave this field blank!'
    %div
      = f.button :submit, 'Send message', :class=> "btn btn-primary"

app/views/general/_contactslist.html.haml
%ul
  %li
    %span Telefone:
    91 xxx xx xx
  %li
    %span Email:
    mail@dominio.pt

app/views/general/_serviceslist.html.haml
%ul
    %li Cuidados de Reabilitação
    %li Cuidados de Enfermagem Pontuais
    %li Cuidados Continuados
    %li Cuidados Paleativos            
    %li Massagem Terapêutica

app/views/general/_testemonieslist.html.haml
%p
  “Quer do ponto de vista técnico quer do ponto de vista humano, só posso caracterizar a Humanize como um serviço de excelência. Decisiva para a minha recuperação clínica e reintegração na vida activa. Ou a arte de transformar um episódio doloroso e negativo, em algo rapidamente esquecido e... positivo! O meu obrigado.”

app/views/layouts/_footer.html.haml
%section#clients
  .zerogrid
    %h4 Testemunhos
    = render 'general/testemonieslist'
%section#footer
  %img{:alt => "logo50h", :src => "pictures/logo50h.png"}/
  %p 2014 | Suse Lopes Enfermagem
  %p
  %p powered by domikestudios.com

app/views/layouts/_header.html.haml
%header
  /
    <div class='logo'>
    <img src="pictures/siteLogo.png" alt="logo"/>
    </div>
  %section#title
    .zerogrid.row
      .col-1-2.logo
        %h1 SUSENF - Apoio Domiciliário
      .col-1-2#contacts
        = render 'general/contactslist'        
  %nav.nav-collapse
    %ul
      %li= link_to "início", root_path
      %li= link_to "serviços", pages_services_path
      %li= link_to "testemunhos", pages_testemonies_path
      %li= link_to "FAQ", pages_faq_path      
      %li= link_to "contactos", pages_contacts_path
      / %li= link_to "blog", blog_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
  = render "layouts/header"
  .content
    .zerogrid
      %p.notice= notice
      %p.alert= alert
      = yield
  = render "layouts/footer"

app/views/pages/contacts.html.haml
= provide(:title, 'Contactos')
%h1 Contactos
= render 'general/contactslist'

app/views/pages/faq.html.haml
= provide(:title, 'FAQ')
%h1 Perguntas Frequentes
%p Find me in app/views/pages/faq.html.haml

app/views/pages/home.html.haml
= provide(:title, 'Home')
.col-full.slider
  %h1 SLIDER
.col-1-3.services
  %h2 Serviços
  = render 'general/serviceslist'
  
.col-1-3.area
  %h2 Zona de Abrangência   
  %ul
    %li Coimbra
    %li Lousã
    %li Miranda do Corvo
    %li Penacova
    %li Vila Nova de Poiares            
  

.col-1-3.schedule
  %h2 Horário
  %ul
    %li Dias úteis das 8 às 19 horas
    %li Fins de semana e feriados: consoante marcação prévia
  

.col-1-3.budget
  %h2 Contacte-nos
  %ul
    %li Diga-nos o que necessita e daremos a melhor solução
    

app/views/pages/services.html.haml
= provide(:title, 'Serviços')
%h1 Serviços
= render 'general/serviceslist'

app/views/pages/testemonies.html.haml
= provide(:title, 'Testemunhos')
%h1 Testemunhos
= render 'general/testemonieslist'